version: '3.9'

services:

    laravel-app:
        container_name: laravel_app
        image: local/laravel-starter-kit
        pull_policy: never
        build:
            context: .
            dockerfile: ./.docker/php/dev.dockerfile
        volumes:
            - .:/var/www
            - ./.docker/php/php.dev.ini:/usr/local/etc/php/php.ini
            - ./.docker/coverage:/opt/phpstorm-coverage
        restart: unless-stopped
        networks:
            - laravel-network

    laravel-web:
        container_name: laravel_web
        image: nginx
        volumes:
            - .:/var/www
            - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./.docker/nginx/virtualhost.conf:/etc/nginx/conf.d/default.conf
            - ./.docker/nginx/mailhog.conf:/etc/nginx/conf.d/mailhog.conf
        ports:
            - ${HTTP_PORT:-80}:80
            - ${HTTPS_PORT:-443}:443
        restart: unless-stopped
        depends_on:
            - laravel-app
        secrets:
            - source: server.crt
              target: /run/secrets/server.crt
            - source: server.key
              target: /run/secrets/server.key
        networks:
            - laravel-network

    laravel-db:
        container_name: laravel_db
        image: mariadb:10.10
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
            MYSQL_DATABASE: ${DB_DATABASE:-laravel-dashboard}
            MYSQL_USER: ${DB_USERNAME:-admin}
            MYSQL_PASSWORD: ${DB_PASSWORD:-admin}
        volumes:
            - ./.docker/mysql/db:/var/lib/mysql
        ports:
            - ${DB_PORT:-3306}:3306
        depends_on:
            - laravel-app
        networks:
            - laravel-network

    laravel-redis:
        container_name: laravel_redis
        restart: unless-stopped
        image: redis:7.0
        ports:
            - ${REDIS_PORT:-6379}:6379
        command: >
            --requirepass ${REDIS_PASSWORD:-secret}
        networks:
            - laravel-network

    laravel-mailhog:
        container_name: laravel_mailhog
        image: mailhog/mailhog:v1.0.1
        platform: linux/amd64
        ports:
            - ${MAIL_PORT:-1025}:1025
            - ${MAIL_UI_PORT:-8025}:8025
        networks:
            - laravel-network

    laravel-worker:
        container_name: laravel_worker
        restart: unless-stopped
        image: local/laravel-starter-kit
        pull_policy: never
        depends_on:
            - laravel-rabbitmq
            - laravel-redis
        command: php artisan queue:work --sleep=1 --tries=3
        volumes:
            - .:/var/www
        networks:
            - laravel-network

    laravel-rabbitmq:
        container_name: laravel_rabbitmq
        image: local/rabbitmq
        pull_policy: never
        build:
            context: ./.docker/rabbitmq
            args:
                RABBITMQ_USER: ${RABBITMQ_USER:-guest}
                RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-guest}
                RABBITMQ_PORT: ${RABBITMQ_PORT:-5672}
        hostname: rabbit_node
        ports:
            - ${RABBITMQ_PORT:-5672}:5672
            - ${RABBITMQ_UI_PORT:-15672}:15672
        volumes:
            - ./.docker/rabbitmq/data:/var/lib/rabbitmq
            - ./.docker/rabbitmq/log:/var/log/rabbitmq
        networks:
            - laravel-network

secrets:
    server.crt:
        file: ${SSL_CRT_PATH}
    server.key:
        file: ${SSL_KEY_PATH}

networks:
    laravel-network:
        driver: bridge
