version: '3.9'

services:

  laravel-app:
    container_name: laravel_app
    image: oleksiivelychko/laravelstarterkit
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./.docker/php/production/Dockerfile
    ports:
      - ${HTTP_PORT:-80}:80
      - ${HTTPS_PORT:-443}:443
    environment:
      DOCKER_BUILDKIT: 1
    restart: unless-stopped
    depends_on:
      - laravel-db

  laravel-db:
      container_name: laravel_db
      image: postgres:15-alpine
      restart: unless-stopped
      environment:
          POSTGRES_USER: ${DB_USERNAME:-postgres}
          POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
          POSTGRES_DB: ${DB_DATABASE:-laravel-starter-kit}
      volumes:
          - postgres:/var/lib/postgresql/data
      ports:
          - ${DB_PORT:-5432}:${DB_PORT:-5432}
      command: -p ${DB_PORT:-5432}

volumes:
  postgres:
